CREATE TABLE AUTHOR (
    AUTHOR_ID VARCHAR2(50) PRIMARY KEY,
    AUTHOR_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    AFFILIATION VARCHAR2(200),
    PHONE_NUMBER VARCHAR2(20),
    PASSWORD VARCHAR2(255) NOT NULL
);

CREATE TABLE RESEARCH_FIELD (
    FIELD_ID VARCHAR2(50) PRIMARY KEY,
    FIELD_NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500)
);

CREATE TABLE ADMINISTRATOR (
    ADMIN_ID VARCHAR2(50) PRIMARY KEY,
    ADMIN_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(50)
);

CREATE TABLE REVIEWER (
    REVIEWER_ID VARCHAR2(50) PRIMARY KEY,
    REVIEWER_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    EXPERTISE VARCHAR2(200),
    DESIGNATION VARCHAR2(100),
    AFFILIATION VARCHAR2(200),
    PHONE_NUMBER VARCHAR2(20)
);

CREATE TABLE RESEARCH_PAPER (
    PAPER_ID VARCHAR2(50) PRIMARY KEY,
    AUTHOR_ID VARCHAR2(50) NOT NULL,
    FIELD_ID VARCHAR2(50) NOT NULL,
    PAPER_TITLE VARCHAR2(255) NOT NULL,
    ABSTRACT_TEXT CLOB,
    KEYWORDS VARCHAR2(255),
    SUBMISSION_DATE DATE,
    STATUS VARCHAR2(50) CHECK (STATUS IN ('Submitted', 'Under Review', 'Accepted', 'Rejected', 'Revision Required')),
    FILE_PATH VARCHAR2(255),
    VERSION_NUMBER NUMBER CHECK (VERSION_NUMBER > 0),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID),
    FOREIGN KEY (FIELD_ID) REFERENCES RESEARCH_FIELD(FIELD_ID)
);

CREATE TABLE REVIEW (
    REVIEW_ID VARCHAR2(50) PRIMARY KEY,
    PAPER_ID VARCHAR2(50) NOT NULL,
    REVIEWER_ID VARCHAR2(50) NOT NULL,
    REVIEW_DATE DATE,
    REVIEW_SCORE NUMBER CHECK (REVIEW_SCORE BETWEEN 1 AND 10),
    RECOMMENDATION VARCHAR2(50) CHECK (RECOMMENDATION IN ('Accept', 'Minor Revision', 'Major Revision', 'Reject')),
    REVIEWER_COMMENTS CLOB,
    FOREIGN KEY (PAPER_ID) REFERENCES RESEARCH_PAPER(PAPER_ID),
    FOREIGN KEY (REVIEWER_ID) REFERENCES REVIEWER(REVIEWER_ID)
);

CREATE TABLE REVISION (
    REVISION_ID VARCHAR2(50) PRIMARY KEY,
    PAPER_ID VARCHAR2(50) NOT NULL,
    VERSION_NUMBER NUMBER CHECK (VERSION_NUMBER > 0),
    UPLOAD_DATE DATE,
    REVISED_FILE VARCHAR2(255),
    REMARKS CLOB,
    FOREIGN KEY (PAPER_ID) REFERENCES RESEARCH_PAPER(PAPER_ID)
);

CREATE TABLE FINAL_DECISION (
    DECISION_ID VARCHAR2(50) PRIMARY KEY,
    PAPER_ID VARCHAR2(50) NOT NULL,
    ADMIN_ID VARCHAR2(50) NOT NULL,
    FINAL_STATUS VARCHAR2(50) CHECK (FINAL_STATUS IN ('Accepted', 'Rejected', 'Further Revision')),
    DECISION_DATE DATE,
    COMMENTS CLOB,
    FOREIGN KEY (PAPER_ID) REFERENCES RESEARCH_PAPER(PAPER_ID),
    FOREIGN KEY (ADMIN_ID) REFERENCES ADMINISTRATOR(ADMIN_ID)
);
